version: '3.9'

services:
  db:
    container_name: "db_liga"
    image: "postgres"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=liga
      - POSTGRES_USER=liga
      - POSTGRES_PASSWORD=liga
    volumes:
      - db_data:\postgres_data

volumes:
  db_data: